-- ===========================================================================
--  AgriSense — Supabase / PostgreSQL schema
--  Paste this whole file into  Supabase Dashboard > SQL Editor > New query > Run
--  Then:  cd backend && python -m app.seed
-- ===========================================================================

create extension if not exists "pgcrypto";

-- ------------------------------------------------------------------ farms ---
create table if not exists farms (
  id            text primary key,
  name          text not null,
  owner_name    text not null,
  phone         text,
  village       text,
  district      text,
  state         text,
  lat           double precision not null,
  lon           double precision not null,
  area_ha       numeric(10,2) not null default 0,
  soil_type     text not null,
  language      text not null default 'en',
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------------------------ plots ---
create table if not exists plots (
  id                    text primary key,
  farm_id               text not null references farms(id) on delete cascade,
  name                  text not null,
  crop                  text not null,
  variety               text,
  area_ha               numeric(10,2) not null default 0,
  sowing_date           date not null,
  expected_harvest_date date,
  days_after_sowing     integer not null default 0,
  growth_stage          text,
  irrigation_type       text,
  soil_type             text,
  centroid_lat          double precision,
  centroid_lon          double precision,
  geometry              jsonb,              -- GeoJSON Polygon
  stress_index          numeric(5,3) default 0,
  created_at            timestamptz not null default now()
);
create index if not exists plots_farm_idx on plots(farm_id);

-- -------------------------------------------------------- sensor_readings ---
create table if not exists sensor_readings (
  id              bigint generated by default as identity primary key,
  plot_id         text not null references plots(id) on delete cascade,
  ts              date not null,
  soil_moisture   numeric(6,4),             -- volumetric v/v
  soil_ph         numeric(4,2),
  soil_temp       numeric(5,2),
  soil_ec         numeric(6,3),             -- dS/m
  air_temp_max    numeric(5,2),
  air_temp_min    numeric(5,2),
  humidity        numeric(5,1),
  rainfall_mm     numeric(7,2),
  wind_kph        numeric(5,1),
  et0_mm          numeric(5,2),
  leaf_wetness_hr numeric(4,1),
  unique (plot_id, ts)
);
create index if not exists sensor_plot_ts_idx on sensor_readings(plot_id, ts desc);

-- ------------------------------------------------------ satellite_scenes ---
create table if not exists satellite_scenes (
  id                bigint generated by default as identity primary key,
  plot_id           text not null references plots(id) on delete cascade,
  capture_date      date not null,
  platform          text default 'Sentinel-2 L2A',
  tile_id           text,
  band_blue         numeric(7,4),
  band_red          numeric(7,4),
  band_nir          numeric(7,4),
  band_swir         numeric(7,4),
  ndvi              numeric(7,4),
  evi               numeric(7,4),
  savi              numeric(7,4),
  ndwi              numeric(7,4),
  ndre              numeric(7,4),
  lai               numeric(7,3),
  chlorophyll_index numeric(7,3),
  cloud_pct         numeric(5,1),
  resolution_m      integer default 10,
  unique (plot_id, capture_date)
);
create index if not exists scenes_plot_date_idx on satellite_scenes(plot_id, capture_date desc);

-- -------------------------------------------------------- weather_forecast ---
create table if not exists weather_forecast (
  id               bigint generated by default as identity primary key,
  plot_id          text not null references plots(id) on delete cascade,
  forecast_date    date not null,
  temp_max         numeric(5,1),
  temp_min         numeric(5,1),
  rainfall_mm      numeric(7,1),
  rain_probability numeric(5,1),
  humidity         numeric(5,1),
  wind_kph         numeric(5,1),
  wind_dir         text,
  et0_mm           numeric(5,2),
  source           text,
  unique (plot_id, forecast_date)
);

-- ---------------------------------------------------- cultivation_history ---
create table if not exists cultivation_history (
  id                  bigint generated by default as identity primary key,
  plot_id             text not null references plots(id) on delete cascade,
  season              text,
  year                integer not null,
  crop                text,
  variety             text,
  yield_t_ha          numeric(8,3),
  season_rainfall_mm  numeric(8,1),
  fertilizer_n_kg_ha  numeric(8,1),
  fertilizer_p_kg_ha  numeric(8,1),
  fertilizer_k_kg_ha  numeric(8,1),
  irrigation_mm       numeric(8,1),
  mean_ndvi           numeric(7,4),
  pest_incidence      integer default 0,
  unique (plot_id, year, season)
);

-- ---------------------------------------------------------- market_prices ---
create table if not exists market_prices (
  id               bigint generated by default as identity primary key,
  crop             text not null,
  mandi            text not null,
  price_date       date not null,
  modal_price_qtl  numeric(12,2),
  min_price_qtl    numeric(12,2),
  max_price_qtl    numeric(12,2),
  arrivals_tonnes  numeric(10,1),
  unique (crop, mandi, price_date)
);

-- --------------------------------------------------------- AI output tables ---
create table if not exists predictions (
  id          uuid primary key default gen_random_uuid(),
  plot_id     text references plots(id) on delete cascade,
  model       text not null,
  kind        text,
  value       numeric(14,5),
  unit        text,
  confidence  numeric(5,3),
  features    jsonb,
  explanation jsonb,
  created_at  timestamptz not null default now()
);
create index if not exists predictions_plot_idx on predictions(plot_id, created_at desc);

create table if not exists advisories (
  id                 uuid primary key default gen_random_uuid(),
  plot_id            text references plots(id) on delete cascade,
  category           text not null,
  title              text not null,
  message_en         text,
  message_localised  text,
  language           text default 'en',
  priority           text default 'Medium',
  confidence         numeric(5,3),
  evidence           jsonb,
  status             text default 'issued',
  created_at         timestamptz not null default now()
);
create index if not exists advisories_plot_idx on advisories(plot_id, created_at desc);

create table if not exists sms_outbox (
  id          uuid primary key default gen_random_uuid(),
  plot_id     text references plots(id) on delete cascade,
  phone       text,
  body        text not null,
  lang        text default 'en',
  status      text default 'queued',
  created_at  timestamptz not null default now()
);

-- ------------------------------------------------------------------ views ---
create or replace view v_latest_scene as
select s.* from satellite_scenes s
join (select plot_id, max(capture_date) d from satellite_scenes group by plot_id) m
  on m.plot_id = s.plot_id and m.d = s.capture_date;

create or replace view v_plot_dashboard as
select p.id as plot_id, p.name, p.crop, p.variety, p.area_ha, p.growth_stage,
       f.district, f.state, f.owner_name, f.phone,
       ls.ndvi, ls.ndwi, ls.lai, ls.capture_date as last_scene,
       (select soil_moisture from sensor_readings r
         where r.plot_id = p.id order by ts desc limit 1) as soil_moisture,
       (select soil_ph from sensor_readings r
         where r.plot_id = p.id order by ts desc limit 1) as soil_ph
from plots p
join farms f on f.id = p.farm_id
left join v_latest_scene ls on ls.plot_id = p.id;

-- ---------------------------------------------------- row level security ---
-- The Python backend uses the service-role key, so RLS below is the safe
-- default for any direct browser access with the anon key: read-only.
alter table farms               enable row level security;
alter table plots               enable row level security;
alter table sensor_readings     enable row level security;
alter table satellite_scenes    enable row level security;
alter table weather_forecast    enable row level security;
alter table cultivation_history enable row level security;
alter table market_prices       enable row level security;
alter table predictions         enable row level security;
alter table advisories          enable row level security;
alter table sms_outbox          enable row level security;

do $$
declare t text;
begin
  foreach t in array array['farms','plots','sensor_readings','satellite_scenes',
                           'weather_forecast','cultivation_history','market_prices',
                           'predictions','advisories','sms_outbox']
  loop
    execute format('drop policy if exists %I on %I', t || '_read', t);
    execute format('create policy %I on %I for select using (true)', t || '_read', t);
  end loop;
end $$;
